In [1]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [2]:
import numpy as np

In [7]:
a=np.random.randint(1,101, size=(3,3))

In [8]:
a

array([[ 9,  1, 37],
       [68, 18, 77],
       [40, 90, 13]], dtype=int32)

In [9]:
a.T

array([[ 9, 68, 40],
       [ 1, 18, 90],
       [37, 77, 13]], dtype=int32)

In [10]:
arr= np.random.randint(1,101, size=(3,3))

In [11]:
arr

array([[34,  9, 40],
       [50, 69, 70],
       [88, 13, 23]], dtype=int32)

In [12]:
arr.T

array([[34, 50, 88],
       [ 9, 69, 13],
       [40, 70, 23]], dtype=int32)

In [13]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [14]:
arr=np.ones(10)

In [15]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
arr.reshape(2,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
arr.reshape(5,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
arr=np.arange(1,11)

In [20]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [22]:
arr.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [23]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [28]:
arr= np.random.rand(4,4)

In [29]:
arr

array([[0.89685356, 0.61797431, 0.16257269, 0.95388169],
       [0.36533601, 0.50401867, 0.99818725, 0.39573023],
       [0.34297441, 0.03777084, 0.44796633, 0.19170216],
       [0.63626239, 0.25990485, 0.51709672, 0.19442385]])

In [32]:
arr_with_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print("Original 4x4 array:")
print(arr)

print("\nArray with zero border (6x6):")
print(arr_with_border)

Original 4x4 array:
[[0.89685356 0.61797431 0.16257269 0.95388169]
 [0.36533601 0.50401867 0.99818725 0.39573023]
 [0.34297441 0.03777084 0.44796633 0.19170216]
 [0.63626239 0.25990485 0.51709672 0.19442385]]

Array with zero border (6x6):
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.89685356 0.61797431 0.16257269 0.95388169 0.        ]
 [0.         0.36533601 0.50401867 0.99818725 0.39573023 0.        ]
 [0.         0.34297441 0.03777084 0.44796633 0.19170216 0.        ]
 [0.         0.63626239 0.25990485 0.51709672 0.19442385 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [33]:
arr=np.random.rand(4,4)

In [34]:
arr

array([[0.42940046, 0.42684283, 0.95812226, 0.92944657],
       [0.05987264, 0.62454583, 0.52655939, 0.62973349],
       [0.02716288, 0.84596988, 0.20386988, 0.45555037],
       [0.67785621, 0.64018807, 0.9829857 , 0.84205143]])

In [38]:
arr_with_border= np.pad(arr,pad_width=1,mode ='constant',constant_values=0)
print("original  4x4 array:")
print(arr)
print("\narray with zero border(6x6):")
print (arr_with_border)

original  4x4 array:
[[0.42940046 0.42684283 0.95812226 0.92944657]
 [0.05987264 0.62454583 0.52655939 0.62973349]
 [0.02716288 0.84596988 0.20386988 0.45555037]
 [0.67785621 0.64018807 0.9829857  0.84205143]]

array with zero border(6x6):
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.42940046 0.42684283 0.95812226 0.92944657 0.        ]
 [0.         0.05987264 0.62454583 0.52655939 0.62973349 0.        ]
 [0.         0.02716288 0.84596988 0.20386988 0.45555037 0.        ]
 [0.         0.67785621 0.64018807 0.9829857  0.84205143 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [41]:
arr=np.random.rand(4,4)

In [42]:
arr

array([[0.15564578, 0.55042365, 0.1811698 , 0.6382385 ],
       [0.01332451, 0.63613528, 0.17900504, 0.69106976],
       [0.12490404, 0.99595561, 0.94000383, 0.78472234],
       [0.16704625, 0.02877129, 0.62798048, 0.84197163]])

In [46]:
arr_with_border= np.pad(arr,pad_width=1,mode="constant",constant_values=0)
print("original 4x4 array: ")
print(arr)
print("\narray with zero border (6x6):")
print(arr_with_border)

original 4x4 array: 
[[0.15564578 0.55042365 0.1811698  0.6382385 ]
 [0.01332451 0.63613528 0.17900504 0.69106976]
 [0.12490404 0.99595561 0.94000383 0.78472234]
 [0.16704625 0.02877129 0.62798048 0.84197163]]

array with zero border (6x6):
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.15564578 0.55042365 0.1811698  0.6382385  0.        ]
 [0.         0.01332451 0.63613528 0.17900504 0.69106976 0.        ]
 [0.         0.12490404 0.99595561 0.94000383 0.78472234 0.        ]
 [0.         0.16704625 0.02877129 0.62798048 0.84197163 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [47]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [50]:
arr= np.arange(10,61,5)

In [51]:
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [52]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
#(uppercase, lowercase, title case, etc.) to each element.

In [54]:
arr1=np.array(['python', 'numpy', 'pandas'])

In [55]:
arr1

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [57]:
np. char.upper(arr1)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [58]:
np.char.lower(arr1)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [59]:
np.char.title(arr1)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [60]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array

In [64]:
arr=np.array(["Pratiksha", "sheha"])

In [65]:
arr

array(['Pratiksha', 'sheha'], dtype='<U9')

In [69]:
arr1=np.char.join(' ',arr)

In [70]:
arr1

array(['P r a t i k s h a', 's h e h a'], dtype='<U17')

In [72]:
a=np.array(["name","number","sign"])

In [73]:
a

array(['name', 'number', 'sign'], dtype='<U6')

In [74]:
a_spaced= np.char.join(' ',a)

In [76]:
a_spaced

array(['n a m e', 'n u m b e r', 's i g n'], dtype='<U11')

In [77]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [78]:
a=np.array([[3,4,3]])

In [79]:
a

array([[3, 4, 3]])

In [80]:
a.ndim

2

In [82]:
b= np.array([[5,6,7]])

In [83]:
b

array([[5, 6, 7]])

In [84]:
a+b

array([[ 8, 10, 10]])

In [85]:
a*b

array([[15, 24, 21]])

In [86]:
a-b

array([[-2, -2, -4]])

In [87]:

a/b

array([[0.6       , 0.66666667, 0.42857143]])

In [88]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [90]:
identity_matrix = np.eye(5)


In [92]:
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [94]:
Diag_element=np.diag(identity_matrix)

In [95]:
Diag_element

array([1., 1., 1., 1., 1.])

In [96]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array

In [97]:
arr=np.random.randint(0,1000,size=100)

In [98]:
arr

array([547, 437, 784, 429, 565, 225, 558, 473, 781, 392, 659, 428, 755,
       150, 910, 860, 553, 600, 278, 933, 989,  31, 560, 148, 281,  34,
       770, 196, 275, 687, 747, 880,  55, 855, 789, 243, 568, 678, 636,
       670, 110, 235,  58,  35, 533, 393, 505, 464, 923, 600, 563, 579,
       747, 720, 235, 486, 193, 662, 350, 790, 169, 142, 331, 127, 393,
       557,  77, 860, 728, 551,  69, 189, 276, 510, 260, 941, 669,  18,
        92, 713, 788, 538, 977, 462, 505, 813, 276, 371, 480, 672, 230,
       169, 990, 253,  12, 685, 841, 328, 187, 564], dtype=int32)

In [100]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True
prime_numbers = np.array([num for num in arr if is_prime(num)])

In [102]:
prime_numbers

array([547, 659,  31, 281, 563, 193, 331, 127, 557, 941, 977], dtype=int32)

In [103]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [110]:
temp=np.random.randint(15,35, size=28)

In [111]:
temp

array([15, 20, 18, 25, 21, 24, 16, 21, 19, 15, 30, 28, 18, 17, 18, 34, 26,
       26, 34, 33, 33, 17, 28, 15, 34, 20, 34, 15], dtype=int32)

In [115]:
weekly_temp=temp.reshape(4,7)

In [116]:
weekly_temp

array([[15, 20, 18, 25, 21, 24, 16],
       [21, 19, 15, 30, 28, 18, 17],
       [18, 34, 26, 26, 34, 33, 33],
       [17, 28, 15, 34, 20, 34, 15]], dtype=int32)

In [117]:
avg_temp=np.mean(weekly_temp,axis=1)

In [118]:
avg_temp

array([19.85714286, 21.14285714, 29.14285714, 23.28571429])